### ISSUE TITLE
FORMS Toggle: slider here seems to have lost its vertical center

### ISSUE THREAD

**Issue by swanine** [Spiderpig86/Cirrus#112]
**Describe the bug**
slider here seems to have lost its vertical center, if the design is expected to be vertically centered, is a property missing

```css
top: 50%;
```
```scss
.form-ext-toggle__toggler i::after {
    background-color: $cirrus-gray;
    border-radius: 50%;
    height: 16px;
    left: 4px;
    width: 16px;
    transform: translateY(-50%);
    transition: left var(--animation-duration) ease;
    text-align: left;
}
```

**To Reproduce**
[cirrus-ui.com/forms/toggle](https://www.cirrus-ui.com/forms/toggle)
