### ISSUE TITLE
.level.fill-height example in docs isn't performing as expected

### ISSUE THREAD

**Issue by EttinCon** [Spiderpig86/Cirrus#163]
.level.fill-height example in docs isn't performing as expected. 

URL: https://cirrus-ui.netlify.app/layout/level
Screenshots:
![image](https://user-images.githubusercontent.com/32328287/229359154-7f9bc0ca-3701-4da8-87f3-8bb75d430611.png)

**Comment by Spiderpig86** [comment]
Hey @EttinCon! Thanks for the report! I have tested the fix and pushed it. This will be out in the next release 0.7.2. Meanwhile, you can add this snippet to your stylesheets for project using 0.6.2 or newer to fix it on your end.

```scss
	@media screen and (min-width: 768px) {
		.level-right {
			margin-left: 1rem;
		}

		/* Keep all level children the same height */
		.level.fill-height {
			align-items: stretch;
			display: flex;
		}
	}
```
