### ISSUE TITLE
Change default focus and box-shadow color

### ISSUE THREAD

**Issue by Ponkhy** [Spiderpig86/Cirrus#88]
Hello,

i would like to change the color of the focus and maybe box-shadow (see images).

![image1](https://i.imgur.com/ZAEZpwM.png)
![image2](https://i.imgur.com/dqTbcku.png)
![image3](https://i.imgur.com/vT15eWw.png)

How can i change it, since it looks like `--cirrus-primary` doesn't apply on it?

Thank you!

**Comment by Spiderpig86** [comment]
Hey! Thanks for the feedback! I was thinking in version 0.7.0, there can possibly be a dedicated CSS variable that can be overridden for the focus states. Possible change:

```scss
// default.scss
:root {
    --cirrus-focus-size: 0 0 0.1rem 0.15rem;
    --cirrus-focus-color: rgba(240, 61, 77, .13);
}

:focus {
    box-shadow: var(--cirrus-focus-size) var(--cirrus-focus-color);
    outline: none;
}
```

And then, you should be able to slip in the CSS variables you want to use for your box-shadow like this:

```scss

button {
    --cirrus-focus-size: 0 0 0.1rem 0.15rem;
    --cirrus-focus-color: rgba(0, 61, 77, .13);
}
```
